### ISSUE TITLE
Update the Code and the blog with updated storybook documentation and code examples

### ISSUE THREAD

**Issue by abhijitdotsharma** [prateek3255/my-awesome-component-library#2]
I found this article really helpful, and I noticed some details like
`Meta` is now replaced with `ComponentMeta` and `ComponentStory` in [storybook docs](https://storybook.js.org/docs/react/writing-stories/introduction#using-args) among other things.

Would love for the author to refactor the article and the code examples if time permits.

Thanks for the article once again!

**Comment by prateek3255** [comment]
Thanks for pointing this out @abhijitdotsharma will update the blog.

**Comment by prateek3255** [comment]
Have updated the article:
https://prateeksurana.me/blog/react-component-library-using-storybook-6/
