### ISSUE TITLE
Error when running yarn storybook

### ISSUE THREAD

**Issue by beepsoft** [prateek3255/my-awesome-component-library#3]
Hi,

great article https://prateeksurana.me/blog/react-component-library-using-storybook-6/!

I just tried to run `yarn storybook` and got this error:

https://github.com/storybookjs/storybook/issues/11587

Do you have a way to make it work?

**Comment by beepsoft** [comment]
I tried upgrading to version 7 beta, and this way it seems to work:

`npx storybook@next upgrade --prerelease`

**Comment by prateek3255** [comment]
Yes you are right, was experimenting compiling with newer versions of rollup and just accidentally left the `"type": "module"` there. Removed it now, it should work as expected. Also will update the blog with StoryBook 7 once its stable. Thanks for pointing it out 🙌🏻

**Comment by Benjaminsson** [comment]
I would _love_ to see an update to the blog post now that Storybook 7 is stable!

**Comment by prateek3255** [comment]
Hey @Benjaminsson thanks for pointing out I have updated the article with instructions for Storybook 7. I have also updated the code in the repo for the same and have updated rollup and all its plugins to their latest versions. Checkout the latest article here: https://prateeksurana.me/blog/react-component-library-using-storybook-7/

**Comment by Benjaminsson** [comment]
@prateek3255 You are awesome!!! Learning so much from this tutorial!
